# Generated by Django 4.2.1 on 2023-05-26 14:28

from django.db import migrations

from utils.migrations import AddPeriodicTask


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        AddPeriodicTask(
            'Sync KuCoin',
            'apps.trade.tasks.sync_kucoin',
            'IntervalSchedule',
            every=10,
            period='seconds',
        )
    ]
