# Generated by Django 4.2.1 on 2023-05-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_add_sync_kucoin_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='kc_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='kc_key',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc_id', models.CharField(max_length=24, unique=True)),
                ('kc_created_at', models.DateTimeField()),
                ('src_currency', models.CharField(max_length=63)),
                ('dst_currency', models.CharField(max_length=63)),
                ('price', models.FloatField()),
                ('size', models.FloatField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trade.trader')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc_id', models.CharField(max_length=24, unique=True)),
                ('currency', models.CharField(max_length=63)),
                ('type', models.CharField(max_length=63)),
                ('balance', models.FloatField(default=0.0)),
                ('available', models.FloatField(default=0.0)),
                ('holds', models.FloatField(default=0.0)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='trade.trader')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
