# Generated by Django 4.2.1 on 2023-06-01 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='trade.trader'),
        ),
    ]
