# Generated by Django 4.2.1 on 2023-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_follow_slave'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='kc_margin_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trader',
            name='kc_spot_access',
            field=models.BooleanField(default=False),
        ),
    ]
