# Generated by Django 4.1.9 on 2023-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_order_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], default='sell', max_length=15),
            preserve_default=False,
        ),
    ]
