# Generated by Django 4.1.9 on 2023-06-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_order_side'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='trade_follow_master_slave_uniq',
        ),
        migrations.AddField(
            model_name='follow',
            name='symbol',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('master', 'slave', 'symbol'), name='trade_follow_master_slave_symbol_uniq'),
        ),
    ]
