# Generated by Django 4.1.9 on 2023-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_remove_follow_trade_follow_master_slave_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dst_usd',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='src_usd',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
