# Generated by Django 4.1.9 on 2023-06-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_order_dst_usd_order_src_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=127)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='trade_follow_master_slave_symbol_uniq',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='symbol',
        ),
        migrations.AddField(
            model_name='follow',
            name='max_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='max_trading_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('master', 'slave'), name='trade_follow_master_slave_uniq'),
        ),
        migrations.AddField(
            model_name='followsymbol',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='trade.follow'),
        ),
    ]
